# Generated by Django 6.1.1 on 2026-10-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Number', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=50)),
                ('Pincode', models.IntegerField()),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
