# Generated by Django 6.1.1 on 2026-10-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obanai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Product',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='City',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='Number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(),
        ),
    ]
